apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iberryful.com
spec:
  group: iberryful.com
  version: v1
  scope: Namespaced
  names:
    plural: runners
    singular: runner
    kind: Runner